name = "webtest"
main = ".open-next/worker.js"
compatibility_date = "2026-05-19"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "webtest-db"
database_id = "38c0b8a4-9bdc-4503-80ea-1a6ba0e7a5dc"
